// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function $$Error(props) {
  return React.createElement("div", undefined, "Could not fetch data from api " + props.msg + "");
}

var make = $$Error;

export {
  make ,
}
/* react Not a pure module */
