// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Context from "../Context.bs.js";

function Favorites(props) {
  Context.useGlobalContext(undefined);
  return React.createElement("div", undefined, "Favorites");
}

var make = Favorites;

export {
  make ,
}
/* react Not a pure module */
