// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Context from "../Context.bs.js";

function Favorites(props) {
  var context = Context.useGlobalContext(undefined);
  console.log("Inside Favorites Context is: " + context + "");
  return React.createElement("div", undefined, "Favorites");
}

var make = Favorites;

export {
  make ,
}
/* react Not a pure module */
