// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Meals(props) {
  var meals = props.meals;
  console.log("Size of Array " + String(meals.length) + "");
  return meals.map(function (meal, i) {
              return React.createElement("div", {
                          key: String(i),
                          id: String(i)
                        }, React.createElement("p", undefined, meal.mealName), React.createElement("img", {
                              src: meal.thumbnail
                            }));
            });
}

var make = Meals;

export {
  make ,
}
/* react Not a pure module */
