// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Context from "../Context.bs.js";

function Modal(props) {
  var context = Context.useGlobalContext(undefined);
  console.log("insise Modal Context is: " + context + "");
  return React.createElement("div", undefined, "Modal");
}

var make = Modal;

export {
  make ,
}
/* react Not a pure module */
