// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import '../styles/Spinner.css'
;

function Spinner(props) {
  return React.createElement("div", {
              className: "loader"
            });
}

var make = Spinner;

export {
  make ,
}
/*  Not a pure module */
