// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Spinner(props) {
  return React.createElement("div", undefined, "Getting data from API....");
}

var make = Spinner;

export {
  make ,
}
/* react Not a pure module */
