// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Meals from "./components/Meals.bs.js";
import * as Modal from "./components/Modal.bs.js";
import * as React from "react";
import * as Search from "./components/Search.bs.js";
import * as Context from "./Context.bs.js";
import * as Favorites from "./components/Favorites.bs.js";
import * as Pervasives from "rescript/lib/es6/pervasives.js";

import './styles/App.css'
;

function App(props) {
  var match = Context.useGlobalContext(undefined);
  if (typeof match === "number" || match.TAG === /* GotError */0) {
    return Pervasives.failwith("cannot come here as the root component does not send the call here if we didn't get result");
  } else {
    return React.createElement("main", undefined, React.createElement(Search.make, {}), React.createElement(Favorites.make, {}), React.createElement(Meals.make, {
                    meals: match.meals
                  }), React.createElement(Modal.make, {}));
  }
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
