// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './styles/App.css'
;

function App(props) {
  return React.createElement("div", undefined, "App");
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
