// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Meals from "./Meals.bs.js";
import * as Modal from "./Modal.bs.js";
import * as React from "react";
import * as Search from "./Search.bs.js";
import * as Favorites from "./Favorites.bs.js";

import './styles/App.css'
;

function App(props) {
  return React.createElement("main", undefined, React.createElement(Search.make, {}), React.createElement(Favorites.make, {}), React.createElement(Meals.make, {}), React.createElement(Modal.make, {}));
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
