// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var context = React.createContext("test");

var make = context.Provider;

var Provider = {
  make: make
};

function useGlobalContext(param) {
  return React.useContext(context);
}

export {
  context ,
  Provider ,
  useGlobalContext ,
}
/* context Not a pure module */
