// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as User from "./data/User.bs.js";
import * as React from "react";
import * as Context from "./Context.bs.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as Client from "react-dom/client";

Js_promise2.then(User.getUser(undefined), (function (user) {
        console.log(user);
        var rootElement = document.querySelector("#main");
        if (rootElement == null) {
          return Promise.resolve((console.log("Could not find the main div"), undefined));
        } else {
          return Promise.resolve((Client.createRoot(rootElement).render(React.createElement(React.StrictMode, {
                                children: React.createElement(Context.Provider.make, {
                                      value: user,
                                      children: React.createElement(App.make, {})
                                    })
                              })), undefined));
        }
      }));

export {
  
}
/*  Not a pure module */
