// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ThemeContext from "./ThemeContext.bs.js";

function Meals(props) {
  var context = ThemeContext.useGlobalContext(undefined);
  console.log("Inside Meals Context is: " + context + "");
  return React.createElement("div", undefined, "Meals");
}

var make = Meals;

export {
  make ,
}
/* react Not a pure module */
