// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ThemeContext from "./ThemeContext.bs.js";

function Search(props) {
  var context = ThemeContext.useGlobalContext(undefined);
  console.log("Inside Search Context is: " + context + "");
  return React.createElement("div", undefined, "Search");
}

var make = Search;

export {
  make ,
}
/* react Not a pure module */
